# This is a basic workflow to help you get started with Actions

name: build openwrt for lxc

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # init dev env
    - name: 准备编译环境
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential subversion fakeroot gawk gpg
      
    # Runs a set of commands using the runners shell
    - name: 执行编译
      run: |
        chmod +x build.sh
        ./build.sh
    
    # upload
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: openwrt
        path: bin/
